name: Deploy OpenCPU Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        id: add_ssh_key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update and Upgrade Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.198.161.239 << 'EOF'
          sudo apt-get update -y
          sudo apt-get upgrade -y
          EOF

      - name: Install OpenCPU Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.198.161.239 << 'EOF'
          sudo add-apt-repository ppa:opencpu/opencpu-2.2 -y
          sudo apt-get update
          sudo apt-get install -y opencpu-server
          EOF

      - name: Configure SSL Certificates
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.198.161.239 << 'EOF'
          sudo apt-get install -y certbot python3-certbot-apache
          sudo certbot --apache -n --agree-tos --email matheusmrech2@icloud.com --redirect --no-eff-email -d matheusrechmd.com
          EOF

      - name: Configure OpenCPU
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.198.161.239 << 'EOF'
          echo '{
            "httpcache.post": 300,
            "preload": ["ggplot2", "dplyr"],
            "timelimit.post": 120,
            "rlimit.as": 2147483648,
            "rlimit.fsize": 104857600,
            "rlimit.nproc": 50
          }' | sudo tee /etc/opencpu/server.conf
          sudo apachectl restart
          EOF

      - name: Verify Installation
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.198.161.239 << 'EOF'
          curl -f http://localhost/ocpu/info
          EOF

      - name: Install R Packages
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.198.161.239 << 'EOF'
          sudo R -e "install.packages(c('ggplot2', 'dplyr'))"
          EOF
